// Generated by uniffi-bindgen-react-native
#include "react-native-slh-dsa.h"
#include "bindings/slh_dsa_uniffi.hpp"

namespace slhdsa {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSlhDsaUniffi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}