# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("slh_dsa_uniffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_slh_dsa_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_keypair_generate() != 7757:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_parameter_name() != 63153:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign() != 51560:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign_deterministic() != 23979:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signature_len() != 62991:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signing_key_len() != 40535:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verify() != 22241:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_from_signing_key() != 64766:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_len() != 16179:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_free.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_complete_void.restype = None
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_slh_dsa_uniffi_rust_future_free_void.restype = None
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_keypair_generate.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_keypair_generate.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_parameter_name.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_parameter_name.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign_deterministic.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign_deterministic.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signature_len.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signature_len.restype = ctypes.c_uint64
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signing_key_len.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signing_key_len.restype = ctypes.c_uint64
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verify.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verify.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_from_signing_key.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_from_signing_key.restype = _UniffiRustBuffer
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_len.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_len.restype = ctypes.c_uint64
_UniffiLib.ffi_slh_dsa_uniffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_slh_dsa_uniffi_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_keypair_generate.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_keypair_generate.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_parameter_name.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_parameter_name.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign_deterministic.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_sign_deterministic.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signature_len.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signature_len.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signing_key_len.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_signing_key_len.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verify.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verify.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_from_signing_key.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_from_signing_key.restype = ctypes.c_uint16
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_len.argtypes = (
)
_UniffiLib.uniffi_slh_dsa_uniffi_checksum_func_slh_dsa_verifying_key_len.restype = ctypes.c_uint16

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.







class SlhDsaStatus(enum.Enum):
    
    OK = 0
    
    INVALID_PARAM = 1
    
    INVALID_LENGTH = 2
    
    DECODE_ERROR = 3
    
    VERIFY_FAILED = 4
    


class _UniffiFfiConverterTypeSlhDsaStatus(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return SlhDsaStatus.OK
        if variant == 2:
            return SlhDsaStatus.INVALID_PARAM
        if variant == 3:
            return SlhDsaStatus.INVALID_LENGTH
        if variant == 4:
            return SlhDsaStatus.DECODE_ERROR
        if variant == 5:
            return SlhDsaStatus.VERIFY_FAILED
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == SlhDsaStatus.OK:
            return
        if value == SlhDsaStatus.INVALID_PARAM:
            return
        if value == SlhDsaStatus.INVALID_LENGTH:
            return
        if value == SlhDsaStatus.DECODE_ERROR:
            return
        if value == SlhDsaStatus.VERIFY_FAILED:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == SlhDsaStatus.OK:
            buf.write_i32(1)
        if value == SlhDsaStatus.INVALID_PARAM:
            buf.write_i32(2)
        if value == SlhDsaStatus.INVALID_LENGTH:
            buf.write_i32(3)
        if value == SlhDsaStatus.DECODE_ERROR:
            buf.write_i32(4)
        if value == SlhDsaStatus.VERIFY_FAILED:
            buf.write_i32(5)



class _UniffiFfiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)

@dataclass
class KeyResult:
    def __init__(self, *, status:SlhDsaStatus, verifying_key:bytes):
        self.status = status
        self.verifying_key = verifying_key
        
        

    
    def __str__(self):
        return "KeyResult(status={}, verifying_key={})".format(self.status, self.verifying_key)
    def __eq__(self, other):
        if self.status != other.status:
            return False
        if self.verifying_key != other.verifying_key:
            return False
        return True

class _UniffiFfiConverterTypeKeyResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return KeyResult(
            status=_UniffiFfiConverterTypeSlhDsaStatus.read(buf),
            verifying_key=_UniffiFfiConverterBytes.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeSlhDsaStatus.check_lower(value.status)
        _UniffiFfiConverterBytes.check_lower(value.verifying_key)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeSlhDsaStatus.write(value.status, buf)
        _UniffiFfiConverterBytes.write(value.verifying_key, buf)

@dataclass
class Keypair:
    def __init__(self, *, signing_key:bytes, verifying_key:bytes):
        self.signing_key = signing_key
        self.verifying_key = verifying_key
        
        

    
    def __str__(self):
        return "Keypair(signing_key={}, verifying_key={})".format(self.signing_key, self.verifying_key)
    def __eq__(self, other):
        if self.signing_key != other.signing_key:
            return False
        if self.verifying_key != other.verifying_key:
            return False
        return True

class _UniffiFfiConverterTypeKeypair(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Keypair(
            signing_key=_UniffiFfiConverterBytes.read(buf),
            verifying_key=_UniffiFfiConverterBytes.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterBytes.check_lower(value.signing_key)
        _UniffiFfiConverterBytes.check_lower(value.verifying_key)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterBytes.write(value.signing_key, buf)
        _UniffiFfiConverterBytes.write(value.verifying_key, buf)

@dataclass
class SignResult:
    def __init__(self, *, status:SlhDsaStatus, signature:bytes):
        self.status = status
        self.signature = signature
        
        

    
    def __str__(self):
        return "SignResult(status={}, signature={})".format(self.status, self.signature)
    def __eq__(self, other):
        if self.status != other.status:
            return False
        if self.signature != other.signature:
            return False
        return True

class _UniffiFfiConverterTypeSignResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SignResult(
            status=_UniffiFfiConverterTypeSlhDsaStatus.read(buf),
            signature=_UniffiFfiConverterBytes.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeSlhDsaStatus.check_lower(value.status)
        _UniffiFfiConverterBytes.check_lower(value.signature)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeSlhDsaStatus.write(value.status, buf)
        _UniffiFfiConverterBytes.write(value.signature, buf)

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

@dataclass
class VerifyResult:
    def __init__(self, *, status:SlhDsaStatus, valid:bool):
        self.status = status
        self.valid = valid
        
        

    
    def __str__(self):
        return "VerifyResult(status={}, valid={})".format(self.status, self.valid)
    def __eq__(self, other):
        if self.status != other.status:
            return False
        if self.valid != other.valid:
            return False
        return True

class _UniffiFfiConverterTypeVerifyResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return VerifyResult(
            status=_UniffiFfiConverterTypeSlhDsaStatus.read(buf),
            valid=_UniffiFfiConverterBoolean.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeSlhDsaStatus.check_lower(value.status)
        _UniffiFfiConverterBoolean.check_lower(value.valid)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeSlhDsaStatus.write(value.status, buf)
        _UniffiFfiConverterBoolean.write(value.valid, buf)






class ParameterSetId(enum.Enum):
    
    SHAKE128S = 0
    
    SHAKE128F = 1
    
    SHAKE192S = 2
    
    SHAKE192F = 3
    
    SHAKE256S = 4
    
    SHAKE256F = 5
    
    SHA2_128S = 6
    
    SHA2_128F = 7
    
    SHA2_192S = 8
    
    SHA2_192F = 9
    
    SHA2_256S = 10
    
    SHA2_256F = 11
    


class _UniffiFfiConverterTypeParameterSetId(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ParameterSetId.SHAKE128S
        if variant == 2:
            return ParameterSetId.SHAKE128F
        if variant == 3:
            return ParameterSetId.SHAKE192S
        if variant == 4:
            return ParameterSetId.SHAKE192F
        if variant == 5:
            return ParameterSetId.SHAKE256S
        if variant == 6:
            return ParameterSetId.SHAKE256F
        if variant == 7:
            return ParameterSetId.SHA2_128S
        if variant == 8:
            return ParameterSetId.SHA2_128F
        if variant == 9:
            return ParameterSetId.SHA2_192S
        if variant == 10:
            return ParameterSetId.SHA2_192F
        if variant == 11:
            return ParameterSetId.SHA2_256S
        if variant == 12:
            return ParameterSetId.SHA2_256F
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == ParameterSetId.SHAKE128S:
            return
        if value == ParameterSetId.SHAKE128F:
            return
        if value == ParameterSetId.SHAKE192S:
            return
        if value == ParameterSetId.SHAKE192F:
            return
        if value == ParameterSetId.SHAKE256S:
            return
        if value == ParameterSetId.SHAKE256F:
            return
        if value == ParameterSetId.SHA2_128S:
            return
        if value == ParameterSetId.SHA2_128F:
            return
        if value == ParameterSetId.SHA2_192S:
            return
        if value == ParameterSetId.SHA2_192F:
            return
        if value == ParameterSetId.SHA2_256S:
            return
        if value == ParameterSetId.SHA2_256F:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == ParameterSetId.SHAKE128S:
            buf.write_i32(1)
        if value == ParameterSetId.SHAKE128F:
            buf.write_i32(2)
        if value == ParameterSetId.SHAKE192S:
            buf.write_i32(3)
        if value == ParameterSetId.SHAKE192F:
            buf.write_i32(4)
        if value == ParameterSetId.SHAKE256S:
            buf.write_i32(5)
        if value == ParameterSetId.SHAKE256F:
            buf.write_i32(6)
        if value == ParameterSetId.SHA2_128S:
            buf.write_i32(7)
        if value == ParameterSetId.SHA2_128F:
            buf.write_i32(8)
        if value == ParameterSetId.SHA2_192S:
            buf.write_i32(9)
        if value == ParameterSetId.SHA2_192F:
            buf.write_i32(10)
        if value == ParameterSetId.SHA2_256S:
            buf.write_i32(11)
        if value == ParameterSetId.SHA2_256F:
            buf.write_i32(12)



class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)
def slh_dsa_keypair_generate(param: ParameterSetId) -> Keypair:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeKeypair.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_keypair_generate,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_parameter_name(param: ParameterSetId) -> str:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_parameter_name,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_sign(param: ParameterSetId,signing_key: bytes,msg: bytes,ctx: bytes) -> SignResult:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    
    _UniffiFfiConverterBytes.check_lower(signing_key)
    
    _UniffiFfiConverterBytes.check_lower(msg)
    
    _UniffiFfiConverterBytes.check_lower(ctx)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
        _UniffiFfiConverterBytes.lower(signing_key),
        _UniffiFfiConverterBytes.lower(msg),
        _UniffiFfiConverterBytes.lower(ctx),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeSignResult.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_sign_deterministic(param: ParameterSetId,signing_key: bytes,msg: bytes,ctx: bytes) -> SignResult:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    
    _UniffiFfiConverterBytes.check_lower(signing_key)
    
    _UniffiFfiConverterBytes.check_lower(msg)
    
    _UniffiFfiConverterBytes.check_lower(ctx)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
        _UniffiFfiConverterBytes.lower(signing_key),
        _UniffiFfiConverterBytes.lower(msg),
        _UniffiFfiConverterBytes.lower(ctx),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeSignResult.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_sign_deterministic,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_signature_len(param: ParameterSetId) -> int:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
    )
    _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signature_len,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_signing_key_len(param: ParameterSetId) -> int:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
    )
    _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_signing_key_len,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_verify(param: ParameterSetId,verifying_key: bytes,msg: bytes,ctx: bytes,signature: bytes) -> VerifyResult:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    
    _UniffiFfiConverterBytes.check_lower(verifying_key)
    
    _UniffiFfiConverterBytes.check_lower(msg)
    
    _UniffiFfiConverterBytes.check_lower(ctx)
    
    _UniffiFfiConverterBytes.check_lower(signature)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
        _UniffiFfiConverterBytes.lower(verifying_key),
        _UniffiFfiConverterBytes.lower(msg),
        _UniffiFfiConverterBytes.lower(ctx),
        _UniffiFfiConverterBytes.lower(signature),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeVerifyResult.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verify,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_verifying_key_from_signing_key(param: ParameterSetId,signing_key: bytes) -> KeyResult:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    
    _UniffiFfiConverterBytes.check_lower(signing_key)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
        _UniffiFfiConverterBytes.lower(signing_key),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeKeyResult.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_from_signing_key,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def slh_dsa_verifying_key_len(param: ParameterSetId) -> int:
    
    _UniffiFfiConverterTypeParameterSetId.check_lower(param)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeParameterSetId.lower(param),
    )
    _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_slh_dsa_uniffi_fn_func_slh_dsa_verifying_key_len,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "SlhDsaStatus",
    "ParameterSetId",
    "KeyResult",
    "Keypair",
    "SignResult",
    "VerifyResult",
    "slh_dsa_keypair_generate",
    "slh_dsa_parameter_name",
    "slh_dsa_sign",
    "slh_dsa_sign_deterministic",
    "slh_dsa_signature_len",
    "slh_dsa_signing_key_len",
    "slh_dsa_verify",
    "slh_dsa_verifying_key_from_signing_key",
    "slh_dsa_verifying_key_len",
]