// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-slh-dsa.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SlhDsaSpec.h"

@interface SlhDsa : NSObject <NativeSlhDsaSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SlhDsa : NSObject <RCTBridgeModule>
#endif

@end